### ISSUE TITLE
[Bug] Can't load a layer exported from ATT&CK Navigator

### ISSUE THREAD

**Issue by Vayper** [mitre-attack/mitreattack-python#55]
## Expected Behavior

No error while importing a layer from ATT&CK Navigator
The zipped layer is here for reference : [layer.zip](https://github.com/mitre-attack/mitreattack-python/files/8112109/layer.zip)
## Actual Behavior

An error is raised, and the layer is not loaded :
``` log
[Layer] - AttributeError encountered ['#ff6666ff' is not in web format. Need 3 or 6 hex digit.]. Unable to load.
[Layer] - Full Traceback - Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\mitreattack\navlayers\core\layer.py", line 97, in _build
    self.__layer._linker(key, self._data[key])
  File "C:\Python310\lib\site-packages\mitreattack\navlayers\core\layerobj.py", line 446, in _linker
    self.gradient = data
  File "C:\Python310\lib\site-packages\mitreattack\navlayers\core\layerobj.py", line 221, in gradient
    self.__gradient = Gradient(gradient['colors'], gradient['minValue'], gradient['maxValue'])
  File "C:\Python310\lib\site-packages\mitreattack\navlayers\core\gradient.py", line 20, in __init__
    self.maxValue = maxValue
  File "C:\Python310\lib\site-packages\mitreattack\navlayers\core\gradient.py", line 52, in maxValue
    self._compute_curve()
  File "C:\Python310\lib\site-packages\mitreattack\navlayers\core\gradient.py", line 64, in _compute_curve
    s_c = colour.Color(self.colors[index-1])
  File "C:\Python310\lib\site-packages\colour.py", line 988, in __init__
    self.web = color if color else 'black'
  File "C:\Python310\lib\site-packages\colour.py", line 1006, in __setattr__
    fc(value)
  File "C:\Python310\lib\site-packages\colour.py", line 1084, in set_web
    self.hex = web2hex(value)
  File "C:\Python310\lib\site-packages\colour.py", line 670, in web2hex
    raise AttributeError(
AttributeError: '#ff6666ff' is not in web format. Need 3 or 6 hex digit.
```
## Steps to Reproduce the Problem

  1. Go to https://mitre-attack.github.io/attack-navigator/
  2. Create an empty enterprise layer
  3. Download the layer into `layer.json`
  4. Load the layer using Python

      ``` python
      from mitreattack.navlayers.core.layer import Layer
      
      test = Layer()
      test.from_file("layer.json")
      ```
 5. Observe the console output

**Comment by ArtificialErmine** [comment]
Thanks for bringing this to our attention! It looks like the export format for navigator may have been updated slightly, which shouldn't be too hard to address.

**Comment by ArtificialErmine** [comment]
@Vayper We've pushed version 1.4.4 out the door, which should resolve the problem. Thanks for reporting this!
